name: Staging Deployment

on:
  push:
    branches: [development]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Deployment
    steps:
      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEV_HOST }}
          username: ${{ secrets.DEV_USER }}
          key: ${{ secrets.DEV_KEY }}
          port: 22
          script: |
            cd /var/www/html/hellowork-edu
            git checkout staging
            git pull
            composer install
            npm i
            npm run build
